[tool.poetry]
name = "pythondocker1"
version = "0.1.0"
description = ""
authors = ["Rezwanul Islam <rezwanul7@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
